### ISSUE TITLE
Some example

### ISSUE THREAD

**Issue by Faliszek** [janestreet/postgres_async#1]
Hi, 

Thank you very much for your work, the api looks really cool!

But im struggle to get any data with it, do you mind provide some example how get data from simple query? I tried something like this  (I try to use it with ReasonML)

```
  Postgres_async.with_connection(~database="my_database", p =>
    Postgres_async.query(
      p,
      ~parameters=[||],
      ~handle_row=myFunction,
      "select * from my_table",
    )
  )
```

But im stuck with how can I map `Async.Deffered.t(Core.Or_error.t('a))` to get some values from my query?

Thanks in advance.

Cheers

**Comment by danielrichman** [comment]
In order to use postgres_async you must be running the [async scheduler](https://github.com/janestreet/async). Exactly how you start the scheduler and schedule a job that ultimately executes your query depends on your application.

Rows returned by your query are passed to the handle_row callback function. Indeed, the return type of the query function does not contain the query results: it's just a unit Or_error.t Deferred.t that becomes determined with Ok () (if and) when your query successfully completes; when the callback has seen all the rows it will see.

There's an example of this usage here, where the results of the query are printed to stdout: https://github.com/janestreet/postgres_async/blob/1c2a3c43031e24c8c1effcf699ce23a42c408b56/test/test_smoke.ml#L6

**Comment by Faliszek** [comment]
Awesome, thanks a lot, i will dig into that ;)
